### ISSUE TITLE
Not respect cache headers

### ISSUE THREAD

**Issue by egeloen** [php-http/cache-plugin#19]
Hey!

It seems since the last changes, I'm not able to don't consider headers at all.

Here, my set up:

``` php
$this->client = new PluginClient(new Client(), [
    new ErrorPlugin(),
    new CachePlugin(
        new FilesystemAdapter('', 0, __DIR__.'/cache'),
        new GuzzleStreamFactory(),
        ['respect_cache_headers' => false]
    ),
]);
```

After debuggint it, I would update https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L78 by:

``` php
if (!$this->config['respect_cache_headers'] || (isset($data['expiresAt']) && time() < $data['expiresAt'])) {
```

WDYT?

**Comment by Nyholm** [comment]
Using your code will not respect the `default_ttl`. I've created a patch (#20) for this issue. Please try it and give some feedback.

**Comment by dbu** [comment]
that would mean that respect_cache_headers=false leads to infinite cache
lifetime. when respect is false, we return the default_ttl, so max age
should become default ttl always:
https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L208

so either the default ttl is wrong, or you have old cache entries that
miss the expiresAt entry. or we have some bug that makes us calculate
expiresAt incorrectly, or we dont store it as we should.

**Comment by Nyholm** [comment]
Here are some config for **desired** behavior. Currently this is broken but #20 will fix it. 

#### Config 1)

respect_cache_headers: true (default)
default_ttl: null  (default)
cache_lifetime: 30 days  (default)

We cache the items for one month unless they are updated.
We cache the response for whatever it says in the headers.

#### Config 2)

respect_cache_headers: false
default_ttl: null  (default)
cache_lifetime: 30 days  (default)

We cache the items for one month.
We cache the response for same length as the cache item.

#### Config 3)

respect_cache_headers: false
default_ttl: null  (default)
cache_lifetime: null

We cache the items forever.
We cache the response for same length as the cache item.

#### Config 4)

respect_cache_headers: false
default_ttl: 3600
cache_lifetime: null

We cache the items forever
We cache the response for one hour, then we ask the server if the cache is still valid. 

#### Config 5)

respect_cache_headers: false
default_ttl: 3600
cache_lifetime: 30 days  (default)

We cache the items for one month.
We cache the response for one hour, then we ask the server if the cache is still valid. 
If we have not used the cache item in a month it will be deleted.

**Comment by egeloen** [comment]
It would be nice to have this explanation in the doc :)

**Comment by Nyholm** [comment]
FYI https://github.com/php-http/documentation/issues/144
