### ISSUE TITLE
PSR 16 cache plugin

### ISSUE THREAD

**Issue by nagibyro** [php-http/cache-plugin#23]
| Q            | A
| ------------ | ---
| Bug?         | no|yes
| New Feature? |yes

I know this library calls out it's specifically a psr 6 caching plugin -- so I wasn't sure if I should put this here or on the main HTTP libraries issues list. Since [psr 16](http://www.php-fig.org/psr/psr-16/) the simple cache interface has been accepted by the FIG I was wondering if it was possible to have this plugin support both? The main rationale being since there are two standards its possible for projects to be using a caching library that uses psr 16 but not psr 6.

**Comment by dbu** [comment]
we should support PSR-16 for sure. i assume that PSR-6 is not a strict
superset of PSR-16, so we need two different implementations. i guess
there are two aproaches:

* one plugin, and an adapter that dumbs down a PSR-6 cache to behave as
PSR-16
* version two of this plugin, that is only for PSR-16 and provide the
dumbing-down adapter separately
* an abstract base class and two plugin classes that provide the methods
that interact with the cache

i think i prefer the second one. that would allow us to correctly model
the dependencies in composer.json. if we provide the adapter in this
package, we need to depend on both psr-6 and 16.

**Comment by Nyholm** [comment]
We (php-cache) has already created such adapter. See https://github.com/php-cache/simple-cache-bridge

I also think it would be quite easy to support both cache PSRs in this lib. (At least the current code base)

**Comment by GrahamCampbell** [comment]
Symfony now has a cache bridge too, and I am using it in production. I think this issue can be closed tbh.
