### ISSUE TITLE
Detect if the cache can be hitted in an other plugin

### ISSUE THREAD

**Issue by egeloen** [php-http/cache-plugin#28]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes
| Version      | ~

Hey!

While working on egeloen/ivory-google-map#221 which will allow to slow down http requests according to Google rates limits, I'm facing a little issue about the cache plugin.

Basically, the plugin I wrote use `usleep` when needed and in some applications, end users will also use the cache plugin in order to reduce its http requests (allowing to reduce daily quota as well as :moneybag: if it pays for qps/shared quota increase).

In tests, I rely on both plugins and my plugin is trigerring `usleep` call whereas it should not since the response comes from the cache and technically, the Google API has not been reached.

I have read the cache plugin code and I can't see anything allowing me to easily detect such case. For now, the only solution I see it to replicate how the cache plugin generates its cache key and check in the cache entry is available in the pool.

Do you see how I can deal with such feature?

**Comment by dbu** [comment]
what if you put your plugin into the chain after the cache plugin? would
it then not only see "real" requests? or am i missing something?

i assume using the Age header as indicator is not reliable as that could
have been added somewhere upstream? either way, i would not mind having
a config flag to enable a header that tells wether the response is a
cache hit or cache miss. (afaik there is no RFC for this, but something
like Cache-Status: Hit|Miss would be ok.)

**Comment by egeloen** [comment]
@dbu Thanks for your answeer :) Putting the cache plugin at the beginning of the chain is the way to go if the cache plugin adds an header I can detect further on the request in order to not activate the `usleep` calls. But AFAIK, the current state of plugin don't add such king of headers.

I will make a PR during the week in order to add a `Cache-Status` header as you propose.

**Comment by Nyholm** [comment]
Im not sure I understand. The usleep call is in another plugin, right?
If the cache plugin is before the usleep plugin, then the usleep plugin will never see the request if it was a cache hit.

**Comment by egeloen** [comment]
Indeed, I re-read the code and a `FullfiledPromise` is immediatey returned [here](https://github.com/php-http/cache-plugin/blob/master/src/CachePlugin.php#L136), so, let's close it :) I just need to put the cache plugin at the beginning of the chain. I should stop doing open source when it becomes too late :)

**Comment by dbu** [comment]
dont worry. the good thing is you do open source and talk about what you
do, letting you get feedback before losing time, rather than after...
