### ISSUE TITLE
Easy way to only enable etag caching

### ISSUE THREAD

**Issue by GrahamCampbell** [php-http/cache-plugin#42]
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | yes

It would be really cool to have a way to tell the cache plugin to only cache using etags, and ignore anything else, even if valid cache headers with future expiry.

**Comment by GrahamCampbell** [comment]
I guess what I want is to always send the request here:

![image](https://user-images.githubusercontent.com/2829600/28748613-d10576f6-74b3-11e7-9f69-4f00919769e5.png)

**Comment by dbu** [comment]
we have a [configuration](https://github.com/php-http/cache-plugin/blob/104126fc140e7f851f3c1a828ba819110e72616c/src/CachePlugin.php#L60) to tell which cache instructions to respect. if you remove everything there, would it already work as you want it? i feel that if that does not work, it might be a bugfix to make that possible.

**Comment by kelunik** [comment]
Just because I'm curious, what's the use case?
