### ISSUE TITLE
Tag for 1.6.0 is missing

### ISSUE THREAD

**Issue by OndraM** [php-http/cache-plugin#54]
Hi,
it seems there is no tag for version 1.6.0, even though there is record for it in readme.

IMHO the tag 1.6.0 should point to 5ae8a805966987a12f5185897914c2966acdf09e .

**Comment by GrahamCampbell** [comment]
I don't think there's meant to be a 1.6.0 tag yet. I think the contributor in the PR that was merged added a release date to change in the changelog file, and it was merged without being updated.

**Comment by OndraM** [comment]
I'm not quite sure, this is also possible explanation - in this case this could be closed, but the changelog should be adjusted to contain `Unreleased` section in the place of `1.6.0`.

**Comment by sagikazarmark** [comment]
Fixed in https://github.com/php-http/cache-plugin/commit/a250aa2f14a49884c69405e99877cc0947c8d54a

Thanks!
