### ISSUE TITLE
Support for ignoring/limiting max age

### ISSUE THREAD

**Issue by GrahamCampbell** [php-http/cache-plugin#59]
Sometimes the max age can be large, resulting in the total cache size becoming absolutely massive because there's loads of data with long TTLs. It would be convenient to have the TTL be the minimum out of the default ttl and the max age, instead of the sum, perhaps?

I think the way to get around this for now is going to be wrap up the psr cache in a class that limits the TTL.

**Comment by dbu** [comment]
that really depends on the scenario. in my eyes it should be up to the cache implementation to evict old entries when it is using up too much space. e.g. redis is able to do that afaik.

i would not tie such a thing to default ttl, but could see supporting a hard upper limit for cache lifetime that the plugin could use as min($maxCacheLifetime, $maxAgeHeader) or something like that. the default behaviour would stay the same, but if you configure max cache lifetime, it would do the min thingy. wdyt?

**Comment by GrahamCampbell** [comment]
> the plugin could use as min($maxCacheLifetime, $maxAgeHeader)

Yeh, exactly. For now, I have just implemented the limit within a psr cache proxy.

**Comment by GrahamCampbell** [comment]
I don't know. Maybe the best approach is to do it in the way I've done it, and for the plugin not to have to be responsible for maximum TTLs.

**Comment by dbu** [comment]
that would work too, yep.
