### ISSUE TITLE
[Compatibility] Support psr/cache 2.0

### ISSUE THREAD

**Issue by kozlice** [php-http/cache-plugin#69]
**PHP version**: 8.0.1

**Description**
Installation fails with PHP 8.0.1 & `psr/cache` 2.0.0:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/cache-plugin 1.7.0 requires php ^7.1 -> your php version (8.0.1) does not satisfy that requirement.
    - php-http/cache-plugin 1.7.1 requires psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires php-http/cache-plugin ^1.7 -> satisfiable by php-http/cache-plugin[1.7.0, 1.7.1].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Possible Solution**
Submitted a PR for this.

**Comment by SergioRe** [comment]
???

**Comment by dbu** [comment]
@SergioRe if you have a question, please ask it. if you wonder what about the compatibility, we merged the change in #70 and it is released as 1.7.2

**Comment by SergioRe** [comment]
Hi, I am currently deploying to GCP app engine and it asks me to update to PHP8

You are using the deprecated option "--no-suggest". It has no effect and will break in Composer 3.
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - psr/cache is locked to version 2.0.0 and an update of this package was not requested.
    - psr/cache 2.0.0 requires php >=8.0.0 -> your php version (7.4.22) does not satisfy that requirement.
  Problem 2
    - psr/cache 2.0.0 requires php >=8.0.0 -> your php version (7.4.22) does not satisfy that requirement.
    - kreait/firebase-tokens 1.16.0 requires psr/cache ^1.0|^2.0|^3.0 -> satisfiable by psr/cache[2.0.0].
    - kreait/firebase-tokens is locked to version 1.16.0 and an update of this package was not requested.

**Comment by GrahamCampbell** [comment]
That's not a bug, that's expected. Either you use PHP 8 or you use an older version of the libraries.

**Comment by dbu** [comment]
make sure that the environment in which you build the composer.lock file has the same PHP version (and same version of other things you use, if possible) as the system to which you deploy. otherwise you will run into problems like this.
