### ISSUE TITLE
PSR-7 responses shouldn't be considered as serializable

### ISSUE THREAD

**Issue by nicolas-grekas** [php-http/cache-plugin#81]
In src/CachePlugin.php, PSR-7 responses are serialized as is, except the response body, which is serialized separately.

Recently the PHP engine started to throw deprecations when a resource is found in a serialized data structure.
And this happens to PSR-7 responses: whatever the implementation, their body is a represented as a stream resource internally.
Also, from an abstraction PoV, nothing says in PSR-7 that responses are serializable, which means interop should consider them as non-serializable.

The plugin should be improved to not store PSR-7 objects directly, but intermediate representations that fit a generic cache backend.

**Comment by dbu** [comment]
released as https://github.com/php-http/cache-plugin/releases/tag/1.8.0 (i also created 1.7.6 with small fixes - decided to tag this one as a minor version as there can be performance implications with large streams)

thanks for the contribution @nicolas-grekas
