### ISSUE TITLE
php-http/message-factory is abandoned (deprecation error)

### ISSUE THREAD

**Issue by tacman** [php-http/cache-plugin#85]
**PHP version**: x.y.z (hint: `php --version`)

all

**Description**

Package php-http/message-factory is abandoned, you should avoid using it. Use psr/http-factory instead.

**How to reproduce**

composer install with any pacakge that uses it.

**Possible Solution**

use psr/http-factory instead

**Comment by dbu** [comment]
fixed in #87

**Comment by GrahamCampbell** [comment]
Probably this should be kept open until v2.0.0 is released?

**Comment by jurgenhaas** [comment]
Is there anything that could be done to publish this soon, maybe even in the 1.x branch?

I'm asking because `composer audit` complains about the abandoned package and with composer 2.7 this even let's pipeline fail by default.

**Comment by dbu** [comment]
i tagged the 2.0 release now: https://github.com/php-http/cache-plugin/releases/tag/2.0.0

we still support antique php versions, therefore i did not add strict typing. but lets do that in a version 3 if somebody wants to put in the effort, rather than delay this release.

**Comment by jurgenhaas** [comment]
Nice, thank you. Now we only have to get all the other packages that depend on the 1.0 release to update their constraints to also allow 2.0
